const express = require("express");
const app = express();
const bodyParser = require("body-parser");
const port = process.env.PORT || 3000;
const crypto = require("crypto");
const CryptoJS = require("crypto-js");
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.post("/", (req, res) => {
  try {
    private_key = req.body.private_key;
    longtext = req.body.long_text;
    if (private_key == "") {
      res.send("Private key is blank");
    } else if (longtext == "") {
      res.send("Long text is blank");
    } else {
      //  Encrypt the long text using private key and generate 256 hash
      // var cipher = crypto.createCipher('aes-256-cbc', private_key);
      // var encrypted = cipher.update(longtext, 'utf8', 'hex');
      // encrypted += cipher.final('hex');
      // //  Generate 256 hash
      // var hash = crypto.createHash('sha256').update(encrypted).digest('hex');
      // //  Send the hash and encrypted long text
      // res.send({hash: hash, encrypted_text: encrypted});
      // }
      var hash1 = crypto.createHmac('sha256', private_key).update(longtext).digest('hex');
      var hash = crypto.createHash('sha256').update(longtext+private_key).digest('hex');
    //   convert the hash into plain text using private key in crypto
    
    //   res.status(200).json({message:"Success",});
      // // decrypt hash using private key
      // var text = crypto.
      // console.log(text);
      var ciphertext = CryptoJS.AES.encrypt(longtext, private_key).toString();

      // Decrypt
      var bytes = CryptoJS.AES.decrypt(ciphertext, private_key);
      var originalText = bytes.toString(CryptoJS.enc.Utf8);

        res.status(200).json({ message: "Success", encrypted_text: ciphertext, decrypted_text: originalText,hash:hash,hash1:hash1});
    }
  } catch (err) {
    res.status(500).send("kuch to error hai");
  }
});
app.listen(port, () => {
  console.log(`server is running on port ${port}`);
});
// Generated by Api Generator
// Source: Api_Generator256hash/src/app.js
// Generated at: 2020-05-18T10:53:10.907Z
// Language: javascript
// Path: Api_Generator256hash/src/app.js
