const express = require('express');
const app = express();
const bodyParser = require('body-parser');
const port = process.env.PORT || 3000;
const crypto = require('crypto');
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.post('/', (req, res) => {
    try {
        private_key = req.body.private_key;
        longtext = req.body.long_text;
        if (private_key =="")
        {
            res.send("Private key is blank");
        }
        else if (longtext =="")
        {
            res.send("Long text is blank");
        }
        else{
            //  Encrypt the long text using private key and generate 256 hash
            var hash = crypto.createHmac('sha256', private_key).update(longtext).digest('hex');
            res.send("sucess  "+hash);
        }
    } catch (err) {
        res.status(500).send('kuch to error hai');
    }
});
app.listen(port, () => {
    console.log(`server is running on port ${port}`);
});
// Generated by Api Generator
// Source: Api_Generator256hash/src/app.js
// Generated at: 2020-05-18T10:53:10.907Z
// Language: javascript
// Path: Api_Generator256hash/src/app.js
    
   